"use client";

const tiers = [
  { range: "80 – 100", label: "Amazing!", color: "bg-emerald-500", text: "text-emerald-700", bg: "bg-emerald-50", border: "border-emerald-100", desc: "Lean proteins, vegetables, whole grains, healthy cooking methods" },
  { range: "50 – 79", label: "Good!", color: "bg-blue-500", text: "text-blue-700", bg: "bg-blue-50", border: "border-blue-100", desc: "Balanced everyday meals. e.g. Nasi Lemak, pasta, mixed rice" },
  { range: "25 – 49", label: "Normal", color: "bg-amber-500", text: "text-amber-700", bg: "bg-amber-50", border: "border-amber-100", desc: "Higher in fat or sugar. still okay occasionally" },
  { range: "10 – 24", label: "Needs Focus", color: "bg-red-500", text: "text-red-700", bg: "bg-red-50", border: "border-red-100", desc: "Deep-fried foods, sugary drinks, heavy processed items" },
  { range: "0", label: "Neutral", color: "bg-slate-400", text: "text-slate-600", bg: "bg-slate-50", border: "border-slate-100", desc: "Plain water, unsweetened tea or coffee, or unrecognised items" },
];

export default function NourishScoreModal({ onClose }) {
  return (
    <div className="fixed inset-0 z-[60] flex items-center justify-center p-4 bg-black/40 backdrop-blur-sm" onClick={onClose}>
      <div
        className="bg-white rounded-2xl shadow-2xl w-full max-w-md overflow-hidden max-h-[90dvh] flex flex-col"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="px-6 pt-6 pb-4 border-b border-slate-100 flex items-start justify-between gap-4 flex-shrink-0">
          <div>
            <h2 className="text-lg font-black text-slate-900">What is a Nourish Score?</h2>
            <p className="text-xs text-slate-400 mt-1 leading-relaxed">
              A 0–100 rating generated by AI for each meal you log, based on its nutritional value and cooking method.
            </p>
          </div>
          <button onClick={onClose} className="text-slate-300 hover:text-slate-500 transition-colors flex-shrink-0 mt-0.5">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth="2.5" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Tiers */}
        <div className="px-6 py-4 space-y-2 overflow-y-auto flex-1">
          <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-3">Score Breakdown</p>
          {tiers.map((t) => (
            <div key={t.label} className={`flex items-start gap-3 p-3 rounded-xl border ${t.bg} ${t.border}`}>
              <div className="flex items-center gap-2 w-24 flex-shrink-0 pt-0.5">
                <div className={`w-2.5 h-2.5 rounded-full flex-shrink-0 ${t.color}`} />
                <span className={`text-xs font-black ${t.text}`}>{t.label}</span>
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-[10px] font-black text-slate-400 uppercase tracking-wider mb-0.5">{t.range}</p>
                <p className="text-xs text-slate-600 leading-snug">{t.desc}</p>
              </div>
            </div>
          ))}
        </div>

        {/* Footer note */}
        <div className="px-6 pb-6 flex-shrink-0">
          <div className="bg-slate-50 rounded-xl border border-slate-100 px-4 py-3">
            <p className="text-[11px] text-slate-500 leading-relaxed">
              <span className="font-black text-slate-700">How it works: </span>
              When you finish logging, SimplePlate sends your dish name and portion size to an AI. It estimates macronutrients and assigns a score based on ingredients, cooking method, and sugar content.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
